msgid ""
msgstr "Project-Id-Version: pyload\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2014-07-13 20:53+0200\n"
"PO-Revision-Date: 2014-07-13 15:08-0400\n"
"Last-Translator: pyloadTeam <team@pyload.org>\n"
"Language-Team: Galician\n"
"Language: gl_ES\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: crowdin.net\n"

#: pyLoadCore.py:181
msgid "Received Quit signal"
msgstr "Sinal de saída recibida"

#: pyLoadCore.py:302
#, python-format
msgid "pyLoad already running with pid %s"
msgstr "pyLoad xa está executándose con pid %s"

#: pyLoadCore.py:316
#, python-format
msgid "Failed changing group: %s"
msgstr "Cambio de grupo falido: %s"

#: pyLoadCore.py:326
#, python-format
msgid "Failed changing user: %s"
msgstr "Cambio de usuario falido: %s"

#: pyLoadCore.py:328
msgid "folder for logs"
msgstr "cartafol para os rexistros"

#: pyLoadCore.py:339
msgid "Starting"
msgstr "Comezando"

#: pyLoadCore.py:340
#, python-format
msgid "Using home directory: %s"
msgstr "Usando directorio de inicio: %s"

#: pyLoadCore.py:349
msgid "pycrypto to decode container files"
msgstr "pycrypto para descodificar contedores de ligazóns"

#: pyLoadCore.py:352
msgid "folder for temporary files"
msgstr "cartafol para ficheiros temporais"

#: pyLoadCore.py:357
msgid "folder for downloads"
msgstr "cartafol para as descargas"

#: pyLoadCore.py:360
msgid "OpenSSL for secure connection"
msgstr "OpenSSL para conexión segura"

#: pyLoadCore.py:364
msgid "Moving old user config to DB"
msgstr "Movendo a antiga configuración de usuario á BD"

#: pyLoadCore.py:367
msgid "Please check your logindata with ./pyLoadCore.py -u"
msgstr "Por favor, comprobe os seus datos de inicio de sesión con ./pyLoadCore.py -u"

#: pyLoadCore.py:370
msgid "All links removed"
msgstr "Todas as ligazóns foron eliminadas"

#: pyLoadCore.py:401
#, python-format
msgid "Downloadtime: %s"
msgstr "Tempo de descarga: %s"

#: pyLoadCore.py:411
#, python-format
msgid "Free space: %s"
msgstr "Espazo libre: %s"

#: pyLoadCore.py:431
msgid "Activating Accounts..."
msgstr "Activando Contas..."

#: pyLoadCore.py:437
msgid "Activating Plugins..."
msgstr "Activando Engadidos..."

#: pyLoadCore.py:440
msgid "pyLoad is up and running"
msgstr "pyLoad está funcionando"

#: pyLoadCore.py:459
msgid "restarting pyLoad"
msgstr "reiniciando pyLoad"

#: pyLoadCore.py:463
msgid "pyLoad quits"
msgstr "pyLoad pechouse"

#: pyLoadCore.py:520
#, python-format
msgid "Install %s"
msgstr "Instalar %s"

#: pyLoadCore.py:556
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr "non se puido atopar %(desc)s: %(name)s"

#: pyLoadCore.py:558
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr "no se puido crear %(desc)s: %(name)s"

#: pyLoadCore.py:579
msgid "shutting down..."
msgstr "apagando..."

#: pyLoadCore.py:596
msgid "error while shutting down"
msgstr "produciuse un erro mentres se apagaba"

#: pyLoadCore.py:660
msgid "killed pyLoad from Terminal"
msgstr "pyload terminado dende o Terminal"

#: module/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr "O ficheiro da base de datos eliminouse por ser dunha versión incompatible."

#: module/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr "O ficheiro da base de datos NON se puido converter."

#: module/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr "A base de datos converteuse da v2 á v3."

#: module/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr "A base de datos converteuse da v3 á v4."

#: module/database/DatabaseBackend.py:252
msgid "Converting old Django DB"
msgstr "Convertendo a antiga BD Django"

#: module/database/FileDatabase.py:45
msgid "finished"
msgstr "finalizado"

#: module/database/FileDatabase.py:45
msgid "offline"
msgstr "fora de liña"

#: module/database/FileDatabase.py:45
msgid "online"
msgstr "en liña"

#: module/database/FileDatabase.py:45
msgid "queued"
msgstr "na cola"

#: module/database/FileDatabase.py:45
msgid "skipped"
msgstr "omitido"

#: module/database/FileDatabase.py:45
msgid "waiting"
msgstr "esperando"

#: module/database/FileDatabase.py:45
msgid "temp. offline"
msgstr "temporalmente fora de servicio"

#: module/database/FileDatabase.py:45
msgid "starting"
msgstr "comezando"

#: module/database/FileDatabase.py:45
msgid "failed"
msgstr "falido"

#: module/database/FileDatabase.py:45
msgid "aborted"
msgstr "abortado"

#: module/database/FileDatabase.py:45
msgid "decrypting"
msgstr "descifrando"

#: module/database/FileDatabase.py:45
msgid "custom"
msgstr "personalizado"

#: module/database/FileDatabase.py:45
msgid "downloading"
msgstr "descargando"

#: module/database/FileDatabase.py:45
msgid "processing"
msgstr "procesando"

#: module/database/FileDatabase.py:45
msgid "unknown"
msgstr "descoñecido"

#: module/database/FileDatabase.py:531 module/plugins/hooks/IRCInterface.py:74
#: module/plugins/hooks/XMPPInterface.py:83
#, python-format
msgid "Package finished: %s"
msgstr "Paquete finalizado: %s"

#: module/remote/ThriftBackend.py:39
msgid "Using SSL ThriftBackend"
msgstr "Usando SSL ThriftBackend"

#: module/remote/RemoteManager.py:35
#, python-format
msgid "Remote backend error: %s"
msgstr "Erro remoto do motor: %s"

#: module/remote/RemoteManager.py:82
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr "Iniciando %(name)s: %(addr)s:%(port)s"

#: module/remote/RemoteManager.py:84
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr "Fallou ó cargar o motor %(name)s | %(error)s"

#: module/web/json_app.py:57
#, python-format
msgid "waiting %s"
msgstr "esperando %s"

#: module/web/ServerThread.py:36
msgid "SSL certificates not found."
msgstr "Certificados SSL non encontrados."

#: module/web/ServerThread.py:40
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr "Sentímolo, pero retirámolo soporte para iniciar %s directamente en pyLoad"

#: module/web/ServerThread.py:41
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr "Pode empregar o servidor con fíos que ofrece un bo rendemento e ssl,"

#: module/web/ServerThread.py:42
#, python-format
msgid "of course you can still use your existing %s with pyLoads fastcgi server"
msgstr "por suposto pode seguir empregando o seu %s existente co servidor fastcgi de pyLoad"

#: module/web/ServerThread.py:43
msgid "sample configs are located in the module/web/servers directory"
msgstr "as configuracións de exemplo encóntranse no directorio module/web/servers"

#: module/web/ServerThread.py:49
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr "Non pode usar %(server)s, python-flup non está instalado!"

#: module/web/ServerThread.py:58
#, python-format
msgid "Error importing lightweight server: %s"
msgstr "Erro importando servidor lixeiro: %s"

#: module/web/ServerThread.py:59
msgid "You need to download and compile bjoern, https://github.com/jonashaag/bjoern"
msgstr "Debe descargar e compilar bjoern, https://github.com/jonashaag/bjoern"

#: module/web/ServerThread.py:60
msgid "Copy the boern.so to module/lib folder or use setup.py install"
msgstr "Copie o módulo boern.so ó cartafol module/lib ou use a instalación setup.py"

#: module/web/ServerThread.py:61
msgid "Of course you need to be familiar with linux and know how to compile software"
msgstr "Evidentemente, debe estar familiarizado con linux e saber como compilar software"

#: module/web/ServerThread.py:64
msgid "Server set to threaded, due to known performance problems on windows."
msgstr "Servidor en modo threaded, debido a problemas de rendemento coñecidos en windows."

#: module/web/ServerThread.py:80 module/web/ServerThread.py:103
msgid "This server offers no SSL, please consider using threaded instead"
msgstr "Este servidor non ofrece SSL, por favor considere usar o servidor con fíos no seu lugar"

#: module/web/ServerThread.py:82
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr "Iniciando servidor web incorporado: %(host)s:%(port)d"

#: module/web/ServerThread.py:87
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr "Iniciando servidor web SSL con fíos: %(host)s:%(port)d"

#: module/web/ServerThread.py:91
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr "Iniciando servidor web con fíos: %(host)s:%(port)d"

#: module/web/ServerThread.py:97
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr "Iniciando servidor fastcgi: %(host)s:%(port)d"

#: module/web/ServerThread.py:105
#, python-format
msgid "Starting lightweight webserver (bjoern): %(host)s:%(port)d"
msgstr "Iniciando servidor web lixeiro (bjoern): %(host)s:%(port)d"

#: module/web/pyload_app.py:127
msgid "You dont have permission to access this page."
msgstr "Non ten permisos para acceder a esta páxina."

#: module/web/pyload_app.py:195
msgid "Download directory not found."
msgstr "Non se encontra o directorio de descarga."

#: module/web/pyload_app.py:262 module/web/pyload_app.py:269
msgid "unlimited"
msgstr ""

#: module/web/pyload_app.py:264 module/web/pyload_app.py:271
msgid "not available"
msgstr "non dispoñible"

#: module/web/pyload_app.py:509
msgid "Run pyLoadCore.py -s to access the setup."
msgstr "Execute pyLoadCore.py -s para acceder á instalación."

#: module/network/HTTPDownload.py:245
#, python-format
msgid "Download chunks failed, fallback to single connection | %s"
msgstr "Descarga por partes falida, conexión única de emerxencia| %s"

#: module/PluginThread.py:183
#, python-format
msgid "Download starts: %s"
msgstr "Iniciando descarga: %s"

#: module/PluginThread.py:189
#, python-format
msgid "Download finished: %s"
msgstr "Descarga finalizada: %s"

#: module/PluginThread.py:194 module/PluginThread.py:365
#, python-format
msgid "Plugin %s is missing a function."
msgstr "O engadido %s non atopa ningunha función."

#: module/PluginThread.py:202 module/PluginThread.py:265
#: module/PluginThread.py:382
#, python-format
msgid "Download aborted: %s"
msgstr "Descarga cancelada: %s"

#: module/PluginThread.py:222
#, python-format
msgid "Download restarted: %(name)s | %(msg)s"
msgstr "Descarga reiniciada: %(name)s | %(msg)s"

#: module/PluginThread.py:231 module/PluginThread.py:373
#, python-format
msgid "Download is offline: %s"
msgstr "A descarga está fóra de servizo: %s"

#: module/PluginThread.py:234
#, python-format
msgid "Download is temporary offline: %s"
msgstr "A descarga está temporalmente fora de servizo: %s"

#: module/PluginThread.py:237 module/PluginThread.py:304
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr "Descarga falida: %(name)s | %(msg)s"

#: module/PluginThread.py:254
msgid "Couldn't connect to host or connection reset, waiting 1 minute and retry."
msgstr "No se puido conectar ó servidor ou conexión reiniciada, esperando 1 minuto e tentando de novo."

#: module/PluginThread.py:290
#, python-format
msgid "Download skipped: %(name)s due to %(plugin)s"
msgstr "Descarga omitida: %(name)s debido a %(plugin)s"

#: module/PluginThread.py:361
#, python-format
msgid "Decrypting starts: %s"
msgstr "Comeza o descifrado: %s"

#: module/PluginThread.py:376 module/PluginThread.py:394
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr "Descifrado falido: %(name)s | %(msg)s"

#: module/PluginThread.py:388
#, python-format
msgid "Retrying %s"
msgstr "Reintentando %s"

#: module/PluginThread.py:635
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr "A Obtención de información para %(name)s fallou | %(err)s"

#: module/HookManager.py:90 module/plugins/Hook.py:103
#, python-format
msgid "Error executing hooks: %s"
msgstr "Erro executando as ligazóns: %s"

#: module/HookManager.py:140
#, python-format
msgid "Failed activating %(name)s"
msgstr "Fallou a activación de %(name)s"

#: module/HookManager.py:144
#, python-format
msgid "Activated plugins: %s"
msgstr "Engadidos activados: %s"

#: module/HookManager.py:145
#, python-format
msgid "Deactivate plugins: %s"
msgstr "Engadidos desactivados: %s"

#: module/ThreadManager.py:137
#, python-format
msgid "Reconnect Failed: %s"
msgstr "Reconexión Falida: %s"

#: module/ThreadManager.py:176
msgid "Reconnect script not found!"
msgstr "Non se atopou o script de reconexión!"

#: module/ThreadManager.py:182
msgid "Starting reconnect"
msgstr "Iniciando reconexión"

#: module/ThreadManager.py:196
msgid "Failed executing reconnect script!"
msgstr "Fallo executando o script de reconexión!"

#: module/ThreadManager.py:208
#, python-format
msgid "Reconnected, new IP: %s"
msgstr "Conectado de novo, nova dirección IP: %s"

#: module/ThreadManager.py:288
msgid "Not enough space left on device"
msgstr "Non hai suficiente espazo libre no dispositivo"

#: module/plugins/Account.py:85 module/plugins/Account.py:90
#, python-format
msgid "Could not login with account %(user)s | %(msg)s"
msgstr "Non se puido iniciar sesión coa conta %(user)s | %(msg)s"

#: module/plugins/Account.py:86
msgid "Wrong Password"
msgstr "Contrasinal erróneo"

#: module/plugins/Account.py:243
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr "A hora %s ten un formato incorrecto, use: 1:22-3:44"

#: module/plugins/Account.py:269
#, python-format
msgid "Account %s has not enough traffic, checking again in 30min"
msgstr "A conta %s non ten tráfico suficiente, comprobarase outra vez en 30min"

#: module/plugins/Account.py:276
#, python-format
msgid "Account %s is expired, checking again in 1h"
msgstr "A conta %s expirou, compróbea de novo en 1h"

#: module/plugins/crypter/SerienjunkiesOrg.py:126
msgid "Downloadlimit reached"
msgstr "Limite de descargas alcanzado"

#: module/plugins/PluginManager.py:153
#, python-format
msgid "%s has a invalid pattern."
msgstr "%s ten un patrón inválido."

#: module/plugins/PluginManager.py:272
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr "Erro importando %(name)s: %(msg)s"

#: module/plugins/internal/MultiHoster.py:132
msgid "No Hoster loaded"
msgstr "Non se cargou ningún servidor"

#: module/plugins/accounts/BitshareCom.py:38
msgid "Activate direct Download in your Bitshare Account"
msgstr "Active a descarga directa na súa conta de Bitshare"

#: module/plugins/container/LinkList.py:64
msgid "LinkList could not be cleared."
msgstr "A lista de ligazóns non se puido limpar."

#: module/plugins/AccountManager.py:88
msgid "Account settings deleted, due to new config format."
msgstr "Configuración da conta borrada, debido ó formato da nova configuración."

#: module/plugins/hoster/BasePlugin.py:65
msgid "Authorization required (username:password)"
msgstr "Autorización requirida (usuario:contrasinal)"

#: module/plugins/hoster/SimplydebridCom.py:23
#: module/plugins/hoster/RealdebridCom.py:40
#: module/plugins/hoster/FreeWayMe.py:39 module/plugins/hoster/ZeveraCom.py:21
#: module/plugins/hoster/UnrestrictLi.py:52
#: module/plugins/hoster/Vipleech4uCom.py:30
#: module/plugins/hoster/Premium4Me.py:27 module/plugins/hoster/FastixRu.py:36
#: module/plugins/hoster/SimplyPremiumCom.py:52
#: module/plugins/hoster/MegaDebridEu.py:46
#: module/plugins/hoster/AlldebridCom.py:38
#: module/plugins/hoster/LinksnappyCom.py:29
#: module/plugins/hoster/DebridItaliaCom.py:39
#: module/plugins/hoster/RPNetBiz.py:28
#: module/plugins/hoster/MultiDebridCom.py:40
#: module/plugins/hoster/ReloadCc.py:26 module/plugins/hoster/OverLoadMe.py:38
#: module/plugins/hoster/RehostTo.py:25
#: module/plugins/hoster/PremiumizeMe.py:24
#: module/plugins/hooks/RPNetBiz.py:45
#, python-format
msgid "Please enter your %s account or deactivate this plugin"
msgstr ""

#: module/plugins/hoster/FilesMailRu.py:98
#, python-format
msgid "There was HTML Code in the Downloaded File (%s)...redirect error? The Download will be restarted."
msgstr ""

#: module/plugins/hoster/NetloadIn.py:145
#: module/plugins/hoster/NetloadIn.py:169
msgid "File temporarily not available"
msgstr "Arquivo non dispoñible temporalmente"

#: module/plugins/hoster/NetloadIn.py:182
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr "Netload: esperando entre descargas %d s."

#: module/plugins/hoster/NetloadIn.py:213
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr "Netload: esperando captcha %d s."

#: module/plugins/hoster/NetloadIn.py:251
msgid "Downloaded File was empty"
msgstr "O arquivo descargado estaba baleiro"

#: module/plugins/hoster/MegaDebridEu.py:49
#, python-format
msgid "Impossible to connect to %s"
msgstr ""

#: module/plugins/hoster/MegaDebridEu.py:89
#, python-format
msgid "Impossible to debrid %s"
msgstr ""

#: module/plugins/hoster/UploadedTo.py:129
msgid "API key invalid"
msgstr "Clave de API inválida"

#: module/plugins/hoster/UploadedTo.py:153
#, python-format
msgid "%s: Not enough traffic left"
msgstr "%s: Non queda suficiente tráfico"

#: module/plugins/hoster/UploadedTo.py:156
msgid "Traffic exceeded"
msgstr "Tráfico excedido"

#: module/plugins/hoster/RapidshareCom.py:99
msgid "Rapidshare: Traffic Share (direct download)"
msgstr "Rapidshare: Tráfico compartido (descarga directa)"

#: module/plugins/hoster/RapidshareCom.py:126
#: module/plugins/hoster/RapidshareCom.py:193
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr "Xa está descargando dende esta dirección ip, esperando 60 segundos"

#: module/plugins/hoster/RapidshareCom.py:130
msgid "Invalid Auth Code, download will be restarted"
msgstr "Código de Autenticación Inválido, a descarga reiniciarase"

#: module/plugins/hoster/RapidshareCom.py:198
msgid "RapidShareCom: No free slots"
msgstr "RapidShareCom: No quedan espazos dispoñibles"

#: module/plugins/hoster/RapidshareCom.py:201
msgid "You need a premium account for this file"
msgstr "Precisa dunha conta premium para este arquivo"

#: module/plugins/hoster/RapidshareCom.py:203
msgid "Filename reported invalid"
msgstr "Nome do arquivo inválido"

#: module/plugins/hoster/FileserveCom.py:100
msgid "Parallel download error, now waiting 60s."
msgstr "Erro con descargas en paralelo, esperando 60s."

#: module/plugins/hoster/FileserveCom.py:216
msgid "Not logged in."
msgstr "Non iniciou sesión."

#: module/plugins/hoster/MegaNz.py:56
msgid "Decryption failed"
msgstr ""

#: module/plugins/hoster/MegaNz.py:106
msgid "No file key provided in the URL"
msgstr ""

#: module/plugins/hoster/MegaNz.py:118
msgid "Error code:"
msgstr ""

#: module/plugins/Container.py:68
msgid "File not exists."
msgstr "O ficheiro non existe."

#: module/plugins/hooks/UpdateManager.py:97
msgid "Not able to connect server to get updates"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:111
msgid "No pyLoad version available"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:118
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr "***  Nova versión %s de pyLoad dispoñible  ***"

#: module/plugins/hooks/UpdateManager.py:119
msgid "***  Get it here: https://github.com/pyload/pyload/releases  ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:170
#, python-format
msgid "New version of [%(type)s] %(name)s (v%(oldver)s -> v%(newver)s)"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:180
#: module/plugins/hooks/UpdateManager.py:185
#, python-format
msgid "Error when updating plugin %s"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:185
msgid "Version mismatch"
msgstr "Non coincide a versión"

#: module/plugins/hooks/UpdateManager.py:196
#, python-format
msgid "Removed blacklisted plugin: [%(type)s] %(name)s"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:204
msgid "Plugins updated and reloaded"
msgstr "Engadidos actualizados e cargados de novo"

#: module/plugins/hooks/UpdateManager.py:206
msgid "*** Plugins have been updated, pyLoad will be restarted now ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:211
msgid "No plugin updates available"
msgstr "Non hai actualizacións de engadidos dispoñibles"

#: module/plugins/hooks/IRCInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr "Descarga finalizada: %(name)s @ %(plugin)s "

#: module/plugins/hooks/IRCInterface.py:95
#, python-format
msgid "New Captcha Request: %s"
msgstr "Nova Petición de Captcha: %s"

#: module/plugins/hooks/IRCInterface.py:96
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr "Responda con 'c %s texto ó captcha'"

#: module/plugins/hooks/Premium4Me.py:29
msgid "Please add your premium.to account first and restart pyLoad"
msgstr ""

#: module/plugins/hooks/HotFolder.py:81
#, python-format
msgid "Added %s from HotFolder"
msgstr "Engadido %s dende HotFolder"

#: module/plugins/hooks/ExtractArchive.py:94
#, python-format
msgid "No %s installed"
msgstr "%s non instalado"

#: module/plugins/hooks/ExtractArchive.py:96
#: module/plugins/hooks/ExtractArchive.py:101
#, python-format
msgid "Could not activate %s"
msgstr "Non se puido activar %s"

#: module/plugins/hooks/ExtractArchive.py:106
msgid "Activated"
msgstr "Activado"

#: module/plugins/hooks/ExtractArchive.py:108
msgid "No Extract plugins activated"
msgstr "Non se activaron os engadidos de extracción"

#: module/plugins/hooks/ExtractArchive.py:120
#, python-format
msgid "Package %s queued for later extracting"
msgstr "Paquete %s posto na cola para a súa extracción posterior"

#: module/plugins/hooks/ExtractArchive.py:143
#, python-format
msgid "Check package %s"
msgstr "Comprobar paquete %s"

#: module/plugins/hooks/ExtractArchive.py:184
#, python-format
msgid "Extract to %s"
msgstr "Extraer a %s"

#: module/plugins/hooks/ExtractArchive.py:199
msgid "No files found to extract"
msgstr ""

#: module/plugins/hooks/ExtractArchive.py:206
msgid "extracting"
msgstr "extraendo"

#: module/plugins/hooks/ExtractArchive.py:217
msgid "Password protected"
msgstr "Protexido con contrasinal"

#: module/plugins/hooks/ExtractArchive.py:238
msgid "Wrong password"
msgstr "Contrasinal erróneo"

#: module/plugins/hooks/ExtractArchive.py:246
#, python-format
msgid "Deleting %s files"
msgstr "Borrando ficheiros %s"

#: module/plugins/hooks/ExtractArchive.py:253
msgid "Extracting finished"
msgstr "Extracción finalizada"

#: module/plugins/hooks/ExtractArchive.py:259
msgid "Archive Error"
msgstr "Erro de Arquivo"

#: module/plugins/hooks/ExtractArchive.py:261
msgid "CRC Mismatch"
msgstr "O CRC non coincide"

#: module/plugins/hooks/ExtractArchive.py:265
msgid "Unknown Error"
msgstr "Erro Descoñecido"

#: module/plugins/hooks/ExtractArchive.py:317
msgid "Setting User and Group failed"
msgstr "Configuración de Usuario e Grupo falida"

#: module/plugins/hooks/ClickAndLoad.py:75
msgid "Click'N'Load: Port 9666 already in use"
msgstr "Click'N'Load: O porto 9666 xa está en uso"

#: module/plugins/hooks/CaptchaTrader.py:70
#: module/plugins/hooks/Captcha9kw.py:60
#: module/plugins/hooks/ExpertDecoders.py:51
#, python-format
msgid "%s credits left"
msgstr "%s créditos restantes"

#: module/plugins/hooks/CaptchaTrader.py:118
msgid "Could not send response."
msgstr ""

#: module/plugins/hooks/CaptchaTrader.py:136
msgid "Your CaptchaTrader Account has not enough credits"
msgstr "A súa conta de CaptchaTrader non ten créditos suficientes"

#: module/plugins/hooks/LinkdecrypterCom.py:45
msgid "Crypter list not found"
msgstr ""

#: module/plugins/hooks/LinkdecrypterCom.py:59
msgid "Crypter list is empty"
msgstr ""

#: module/plugins/hooks/XMPPInterface.py:91
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr "Descarga finalizada: %(name)s @ %(plugin)s"

#: module/plugins/hooks/Captcha9kw.py:94
#, python-format
msgid "New CaptchaID from upload: %s : %s"
msgstr ""

#: module/plugins/hooks/Captcha9kw.py:130
msgid "Your Captcha 9kw.eu Account has not enough credits"
msgstr ""

#: module/plugins/hooks/ExternalScripts.py:54
#, python-format
msgid "Installed scripts for %s: "
msgstr "Scripts instalados para %s: "

#: module/plugins/hooks/ExternalScripts.py:69
msgid "Script not executable:"
msgstr "Script non executable:"

#: module/plugins/hooks/ExternalScripts.py:80
#, python-format
msgid "Error in %(script)s: %(error)s"
msgstr "Erro en %(script)s: %(error)s"

#: module/plugins/hooks/ExpertDecoders.py:96
msgid "Your ExpertDecoders Account has not enough credits"
msgstr ""

#: module/plugins/hooks/RehostTo.py:32
msgid "Please add your rehost.to account first and restart pyLoad"
msgstr "Por favor, engada primeiro a súa conta rehost.to e reinicie pyLoad"

#: module/plugins/hooks/PremiumizeMe.py:50
msgid "Please add a valid premiumize.me account first and restart pyLoad."
msgstr ""

#: module/plugins/hooks/CaptchaBrotherhood.py:70
#, python-format
msgid "%d credits left"
msgstr ""

#: module/plugins/Plugin.py:389
msgid "Pil and tesseract not installed and no Client connected for captcha decrypting"
msgstr "Pil e tesseract non están instalados e no hai cliente conectado para descifrar o captcha"

#: module/plugins/Plugin.py:393
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr "Non se obtiveron resultados para o captcha no tempo asignado de ningún dos engadidos."

#: module/plugins/Plugin.py:498 module/plugins/Plugin.py:532
#, python-format
msgid "Setting User and Group failed: %s"
msgstr "Configuración de Usuario e Grupo falida: %s"

#: module/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr "Non hai cliente conectado para descifrar o captcha"

#: module/Api.py:330
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr "Engadido o paquete %(name)s que contén %(count)d ligazóns"

#: module/Api.py:593
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr "Engadidos %(count)d ligazóns ó paquete #%(package)d "

#: module/common/JsEngine.py:156
msgid "No js engine detected, please install either Spidermonkey, ossp-js, pyv8 or rhino"
msgstr "Non se detectou ningún motor de js, por favor instale Spidermonkey, ossp-js, pyv8 ou rhino"

