msgid ""
msgstr ""
"Project-Id-Version: pyload\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2014-07-13 20:53+0200\n"
"PO-Revision-Date: 2015-01-18 18:30-0500\n"
"Last-Translator: pyloadTeam <team@pyload.org>\n"
"Language-Team: French\n"
"Language: fr_FR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: crowdin.com\n"
"X-Crowdin-Project: pyload\n"
"X-Crowdin-File: /pyLoad/core.pot\n"

#: pyLoadCore.py:181
msgid "Received Quit signal"
msgstr "Signal d'arrêt reçu"

#: pyLoadCore.py:302
#, python-format
msgid "pyLoad already running with pid %s"
msgstr "pyLoad est déjà lancé avec le pid %s"

#: pyLoadCore.py:316
#, python-format
msgid "Failed changing group: %s"
msgstr "Echec lors du changement de groupe: %s"

#: pyLoadCore.py:326
#, python-format
msgid "Failed changing user: %s"
msgstr "Echec lors du changement d'utilisateur: %s"

#: pyLoadCore.py:328
msgid "folder for logs"
msgstr "dossier des logs"

#: pyLoadCore.py:339
msgid "Starting"
msgstr "Démarrage"

#: pyLoadCore.py:340
#, python-format
msgid "Using home directory: %s"
msgstr "Utilisation du dossier principal : %s"

#: pyLoadCore.py:349
msgid "pycrypto to decode container files"
msgstr "pycrypto pour décoder les fichiers conteneurs"

#: pyLoadCore.py:352
msgid "folder for temporary files"
msgstr "dossier des fichiers temporaires"

#: pyLoadCore.py:357
msgid "folder for downloads"
msgstr "dossier des téléchargements"

#: pyLoadCore.py:360
msgid "OpenSSL for secure connection"
msgstr "OpenSSL pour les connexions sécurisées"

#: pyLoadCore.py:364
msgid "Moving old user config to DB"
msgstr "Déplacement des anciennes configurations utilisateur vers la BDD"

#: pyLoadCore.py:367
msgid "Please check your logindata with ./pyLoadCore.py -u"
msgstr "Vérifiez vos identifiants avec ./pyLoadCore.py -u"

#: pyLoadCore.py:370
msgid "All links removed"
msgstr "Tous les liens ont été supprimés"

#: pyLoadCore.py:401
#, python-format
msgid "Downloadtime: %s"
msgstr "Temps de téléchargement : %s"

#: pyLoadCore.py:411
#, python-format
msgid "Free space: %s"
msgstr "Espace libre : %s"

#: pyLoadCore.py:431
msgid "Activating Accounts..."
msgstr "Activation des comptes ..."

#: pyLoadCore.py:437
msgid "Activating Plugins..."
msgstr "Activation des Extensions..."

#: pyLoadCore.py:440
msgid "pyLoad is up and running"
msgstr "pyLoad est opérationnel"

#: pyLoadCore.py:459
msgid "restarting pyLoad"
msgstr "redémarrage de pyLoad"

#: pyLoadCore.py:463
msgid "pyLoad quits"
msgstr "pyLoad se termine"

#: pyLoadCore.py:520
#, python-format
msgid "Install %s"
msgstr "Installation %s"

#: pyLoadCore.py:556
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr "impossible de trouver %(desc)s: %(name)s"

#: pyLoadCore.py:558
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr "impossible de créer %(desc)s: %(name)s"

#: pyLoadCore.py:579
msgid "shutting down..."
msgstr "en cours de fermeture..."

#: pyLoadCore.py:596
msgid "error while shutting down"
msgstr "erreur lors de l'arrêt"

#: pyLoadCore.py:660
msgid "killed pyLoad from Terminal"
msgstr "fermeture de pyLoad depuis le Terminal"

#: module/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr "La base de données a été supprimé pour cause d'incompatibilité de version."

#: module/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr "La base de données N'a PAS pu être convertie."

#: module/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr "La base de données a été convertie de la v2 vers la v3."

#: module/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr "La base de données a été convertie de la v3 vers la v4."

#: module/database/DatabaseBackend.py:252
msgid "Converting old Django DB"
msgstr "Conversion de l'ancienne BDD Django"

#: module/database/FileDatabase.py:45
msgid "finished"
msgstr "terminé"

#: module/database/FileDatabase.py:45
msgid "offline"
msgstr "hors ligne"

#: module/database/FileDatabase.py:45
msgid "online"
msgstr "en ligne"

#: module/database/FileDatabase.py:45
msgid "queued"
msgstr "en file d'attente"

#: module/database/FileDatabase.py:45
msgid "skipped"
msgstr "ignoré"

#: module/database/FileDatabase.py:45
msgid "waiting"
msgstr "en attente"

#: module/database/FileDatabase.py:45
msgid "temp. offline"
msgstr "temp. hors ligne"

#: module/database/FileDatabase.py:45
msgid "starting"
msgstr "démarrage"

#: module/database/FileDatabase.py:45
msgid "failed"
msgstr "échoué"

#: module/database/FileDatabase.py:45
msgid "aborted"
msgstr "annulé"

#: module/database/FileDatabase.py:45
msgid "decrypting"
msgstr "décryptage"

#: module/database/FileDatabase.py:45
msgid "custom"
msgstr "personnalisé"

#: module/database/FileDatabase.py:45
msgid "downloading"
msgstr "téléchargement en cours"

#: module/database/FileDatabase.py:45
msgid "processing"
msgstr "traitement en cours"

#: module/database/FileDatabase.py:45
msgid "unknown"
msgstr "inconnu"

#: module/database/FileDatabase.py:531 module/plugins/hooks/IRCInterface.py:74
#: module/plugins/hooks/XMPPInterface.py:83
#, python-format
msgid "Package finished: %s"
msgstr "Paquet terminé : %s"

#: module/remote/ThriftBackend.py:39
msgid "Using SSL ThriftBackend"
msgstr "Utilise SSL ThriftBackend"

#: module/remote/RemoteManager.py:35
#, python-format
msgid "Remote backend error: %s"
msgstr "Erreur du backend distant: %s"

#: module/remote/RemoteManager.py:82
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr "Démarre %(name)s: %(addr)s:%(port)s"

#: module/remote/RemoteManager.py:84
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr "Échec du chargement du backend %(name)s | %(error)s"

#: module/web/json_app.py:57
#, python-format
msgid "waiting %s"
msgstr "en attente de %s"

#: module/web/ServerThread.py:36
msgid "SSL certificates not found."
msgstr "Certificats SSL non trouvés."

#: module/web/ServerThread.py:40
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr "Désolé, nous avons arrêté le support du démarrage de %s directement dans pyLoad"

#: module/web/ServerThread.py:41
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr "Vous pouvez utiliser le serveur multitâche qui offre de bonnes performances et le ssl,"

#: module/web/ServerThread.py:42
#, python-format
msgid "of course you can still use your existing %s with pyLoads fastcgi server"
msgstr "bien sur vous pouvez toujours utiliser vos %s existants avec le serveur fastcgi de pyLoad"

#: module/web/ServerThread.py:43
msgid "sample configs are located in the module/web/servers directory"
msgstr "les exemples de configurations sont localisés dans le répertoire module/web/servers"

#: module/web/ServerThread.py:49
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr "Ne peut utiliser %(server)s, python-flup n'est pas installé!"

#: module/web/ServerThread.py:58
#, python-format
msgid "Error importing lightweight server: %s"
msgstr "Erreur lors de l'importation du serveur léger : %s"

#: module/web/ServerThread.py:59
msgid "You need to download and compile bjoern, https://github.com/jonashaag/bjoern"
msgstr "Vous devez télécharger et compiler bjoern, https://github.com/jonashaag/bjoern"

#: module/web/ServerThread.py:60
msgid "Copy the boern.so to module/lib folder or use setup.py install"
msgstr "Copiez le fichier boern.so dans le dossier module/lib, ou utilisez setup.py install"

#: module/web/ServerThread.py:61
msgid "Of course you need to be familiar with linux and know how to compile software"
msgstr "Évidemment vous devez être familier avec Linux et savoir comment compiler un logiciel"

#: module/web/ServerThread.py:64
msgid "Server set to threaded, due to known performance problems on windows."
msgstr "Serveur placé en mode mutlitâche, en raison de problèmes de performances connus sous Windows."

#: module/web/ServerThread.py:80 module/web/ServerThread.py:103
msgid "This server offers no SSL, please consider using threaded instead"
msgstr "Ce serveur ne permet pas la connexion SSL, vous devriez envisager d'utiliser le mode multitâche à la place"

#: module/web/ServerThread.py:82
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr "Démarrage du serveur web interne: %(host)s:%(port)d"

#: module/web/ServerThread.py:87
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr "Démarrage du serveur multitâche web SSL : %(host)s:%(port)d"

#: module/web/ServerThread.py:91
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr "Démarrage du serveur multitâche web : %(host)s:%(port)d"

#: module/web/ServerThread.py:97
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr "Démarrage du serveur webfastcgi : %(host)s:%(port)d"

#: module/web/ServerThread.py:105
#, python-format
msgid "Starting lightweight webserver (bjoern): %(host)s:%(port)d"
msgstr "Démarrage du serveur léger (bjoern) : %(host)s:%(port)d"

#: module/web/pyload_app.py:127
msgid "You dont have permission to access this page."
msgstr "Vous n'avez pas la permission d'accéder à cette page."

#: module/web/pyload_app.py:195
msgid "Download directory not found."
msgstr "Répertoire de téléchargement introuvable."

#: module/web/pyload_app.py:262 module/web/pyload_app.py:269
msgid "unlimited"
msgstr "Illimité"

#: module/web/pyload_app.py:264 module/web/pyload_app.py:271
msgid "not available"
msgstr "non disponible"

#: module/web/pyload_app.py:509
msgid "Run pyLoadCore.py -s to access the setup."
msgstr "Lancez pyLoadCore.py -s pour accéder au paramétrage."

#: module/network/HTTPDownload.py:245
#, python-format
msgid "Download chunks failed, fallback to single connection | %s"
msgstr "Téléchargement par blocs échoué, repli vers une seule connexion | %s"

#: module/PluginThread.py:183
#, python-format
msgid "Download starts: %s"
msgstr "Le téléchargement commence : %s"

#: module/PluginThread.py:189
#, python-format
msgid "Download finished: %s"
msgstr "Téléchargement terminé : %s"

#: module/PluginThread.py:194 module/PluginThread.py:365
#, python-format
msgid "Plugin %s is missing a function."
msgstr "Il manque une fonction au plugin %s."

#: module/PluginThread.py:202 module/PluginThread.py:265
#: module/PluginThread.py:382
#, python-format
msgid "Download aborted: %s"
msgstr "Abandon du téléchargement : %s"

#: module/PluginThread.py:222
#, python-format
msgid "Download restarted: %(name)s | %(msg)s"
msgstr "Téléchargement redémarré : %(name)s | %(msg)s"

#: module/PluginThread.py:231 module/PluginThread.py:373
#, python-format
msgid "Download is offline: %s"
msgstr "Le téléchargement est hors-ligne : %s"

#: module/PluginThread.py:234
#, python-format
msgid "Download is temporary offline: %s"
msgstr "Le téléchargement est temporairement hors ligne: %s"

#: module/PluginThread.py:237 module/PluginThread.py:304
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr "Téléchargement échoué : %(name)s | %(msg)s"

#: module/PluginThread.py:254
msgid "Couldn't connect to host or connection reset, waiting 1 minute and retry."
msgstr "Impossible de se connecter à l'hôte ou connexion perdue, prochain essai dans une minute."

#: module/PluginThread.py:290
#, python-format
msgid "Download skipped: %(name)s due to %(plugin)s"
msgstr "Téléchargement ignoré : %(name)s à cause de %(plugin)s"

#: module/PluginThread.py:361
#, python-format
msgid "Decrypting starts: %s"
msgstr "Démarrage du décryptage : %s"

#: module/PluginThread.py:376 module/PluginThread.py:394
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr "Décryptage échoué : %(name)s | %(msg)s"

#: module/PluginThread.py:388
#, python-format
msgid "Retrying %s"
msgstr "Nouvelle tentative en cours %s"

#: module/PluginThread.py:635
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr "Échec de la collecte des infos pour %(name)s | %(err)s"

#: module/HookManager.py:90 module/plugins/Hook.py:103
#, python-format
msgid "Error executing hooks: %s"
msgstr "Erreur de l'exécution du hook : %s"

#: module/HookManager.py:140
#, python-format
msgid "Failed activating %(name)s"
msgstr "Impossible d'activer %(name)s"

#: module/HookManager.py:144
#, python-format
msgid "Activated plugins: %s"
msgstr "Plugins activés: %s"

#: module/HookManager.py:145
#, python-format
msgid "Deactivate plugins: %s"
msgstr "Plugins désactivés: %s"

#: module/ThreadManager.py:137
#, python-format
msgid "Reconnect Failed: %s"
msgstr "La reconnexion a échoué : %s"

#: module/ThreadManager.py:176
msgid "Reconnect script not found!"
msgstr "Script de reconnexion non trouvé !"

#: module/ThreadManager.py:182
msgid "Starting reconnect"
msgstr "Lancement de la reconnexion"

#: module/ThreadManager.py:196
msgid "Failed executing reconnect script!"
msgstr "Echec d'exécution du script de reconnexion !"

#: module/ThreadManager.py:208
#, python-format
msgid "Reconnected, new IP: %s"
msgstr "Reconnecté, nouvelle IP : %s"

#: module/ThreadManager.py:288
msgid "Not enough space left on device"
msgstr "Il n'y a pas assez de place sur le périphérique"

#: module/plugins/Account.py:85 module/plugins/Account.py:90
#, python-format
msgid "Could not login with account %(user)s | %(msg)s"
msgstr "Impossible de s'identifier avec le compte %(user)s | %(msg)s"

#: module/plugins/Account.py:86
msgid "Wrong Password"
msgstr "Mauvais mot de passe"

#: module/plugins/Account.py:243
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr "Votre heure %s utilise un format incorrect, utilisez 1:22-3:44"

#: module/plugins/Account.py:269
#, python-format
msgid "Account %s has not enough traffic, checking again in 30min"
msgstr "Le compte %s n'a pas assez de trafic, re-vérification dans 30 minutes"

#: module/plugins/Account.py:276
#, python-format
msgid "Account %s is expired, checking again in 1h"
msgstr "Le compte %s a expiré, prochaine vérification dans 1H"

#: module/plugins/crypter/SerienjunkiesOrg.py:126
msgid "Downloadlimit reached"
msgstr "Limite de téléchargement atteinte"

#: module/plugins/PluginManager.py:153
#, python-format
msgid "%s has a invalid pattern."
msgstr "%s a un format invalide."

#: module/plugins/PluginManager.py:272
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr "Erreur d'importation %(name)s : %(msg)s"

#: module/plugins/internal/MultiHoster.py:132
msgid "No Hoster loaded"
msgstr "Aucun hébergeur chargé"

#: module/plugins/accounts/BitshareCom.py:38
msgid "Activate direct Download in your Bitshare Account"
msgstr "Activez le téléchargement direct dans votre compte Bitshare"

#: module/plugins/container/LinkList.py:64
msgid "LinkList could not be cleared."
msgstr "Le fichier links.txt ne peut être vidé."

#: module/plugins/AccountManager.py:88
msgid "Account settings deleted, due to new config format."
msgstr "Paramétrage du compte supprimé, du fait d'un nouveau format de configuration."

#: module/plugins/hoster/BasePlugin.py:65
msgid "Authorization required (username:password)"
msgstr "Autorisation requise (identifiant:mot de passe)"

#: module/plugins/hoster/SimplydebridCom.py:23
#: module/plugins/hoster/RealdebridCom.py:40
#: module/plugins/hoster/FreeWayMe.py:39 module/plugins/hoster/ZeveraCom.py:21
#: module/plugins/hoster/UnrestrictLi.py:52
#: module/plugins/hoster/Vipleech4uCom.py:30
#: module/plugins/hoster/Premium4Me.py:27 module/plugins/hoster/FastixRu.py:36
#: module/plugins/hoster/SimplyPremiumCom.py:52
#: module/plugins/hoster/MegaDebridEu.py:46
#: module/plugins/hoster/AlldebridCom.py:38
#: module/plugins/hoster/LinksnappyCom.py:29
#: module/plugins/hoster/DebridItaliaCom.py:39
#: module/plugins/hoster/RPNetBiz.py:28
#: module/plugins/hoster/MultiDebridCom.py:40
#: module/plugins/hoster/ReloadCc.py:26 module/plugins/hoster/OverLoadMe.py:38
#: module/plugins/hoster/RehostTo.py:25
#: module/plugins/hoster/PremiumizeMe.py:24
#: module/plugins/hooks/RPNetBiz.py:45
#, python-format
msgid "Please enter your %s account or deactivate this plugin"
msgstr "Veuillez entrer votre compte %s ou désactivez ce plugin"

#: module/plugins/hoster/FilesMailRu.py:98
#, python-format
msgid "There was HTML Code in the Downloaded File (%s)...redirect error? The Download will be restarted."
msgstr "Il y avait du code HTML dans le fichier téléchargé (%s)... erreur de redirection ? Le téléchargement va redémarrer."

#: module/plugins/hoster/NetloadIn.py:145
#: module/plugins/hoster/NetloadIn.py:169
msgid "File temporarily not available"
msgstr "Fichier temporairement indisponible"

#: module/plugins/hoster/NetloadIn.py:182
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr "Netload : attente de %d s entre chaque téléchargements."

#: module/plugins/hoster/NetloadIn.py:213
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr "Netload : attendre le captcha pendant %d s."

#: module/plugins/hoster/NetloadIn.py:251
msgid "Downloaded File was empty"
msgstr "Le fichier téléchargé est vide"

#: module/plugins/hoster/MegaDebridEu.py:49
#, python-format
msgid "Impossible to connect to %s"
msgstr "Impossible de se connecter à %s"

#: module/plugins/hoster/MegaDebridEu.py:89
#, python-format
msgid "Impossible to debrid %s"
msgstr "Impossible de débrider %s"

#: module/plugins/hoster/UploadedTo.py:129
msgid "API key invalid"
msgstr "La clé de l'API est invalide"

#: module/plugins/hoster/UploadedTo.py:153
#, python-format
msgid "%s: Not enough traffic left"
msgstr "%s : il ne reste pas assez de trafic"

#: module/plugins/hoster/UploadedTo.py:156
msgid "Traffic exceeded"
msgstr "Le trafic a été dépassé"

#: module/plugins/hoster/RapidshareCom.py:99
msgid "Rapidshare: Traffic Share (direct download)"
msgstr "Rapidshare : partage du trafic (téléchargement direct)"

#: module/plugins/hoster/RapidshareCom.py:126
#: module/plugins/hoster/RapidshareCom.py:193
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr "Un téléchargement est déjà en cours depuis cette adresse, 60 secondes d'attente"

#: module/plugins/hoster/RapidshareCom.py:130
msgid "Invalid Auth Code, download will be restarted"
msgstr "Code d'authentification invalide, le téléchargement va redémarrer"

#: module/plugins/hoster/RapidshareCom.py:198
msgid "RapidShareCom: No free slots"
msgstr "RapidShareCom : aucun slot disponible"

#: module/plugins/hoster/RapidshareCom.py:201
msgid "You need a premium account for this file"
msgstr "Vous avez besoin d'un compte premium pour ce fichier"

#: module/plugins/hoster/RapidshareCom.py:203
msgid "Filename reported invalid"
msgstr "Le nom du fichier est invalide"

#: module/plugins/hoster/FileserveCom.py:100
msgid "Parallel download error, now waiting 60s."
msgstr "Erreur de téléchargement parallèle, attente pendant 60 secondes."

#: module/plugins/hoster/FileserveCom.py:216
msgid "Not logged in."
msgstr "Vous n'êtes pas identifiés."

#: module/plugins/hoster/MegaNz.py:56
msgid "Decryption failed"
msgstr "Le déchiffrement à échoué"

#: module/plugins/hoster/MegaNz.py:106
msgid "No file key provided in the URL"
msgstr "Aucune clé de fichier fournie dans l'URL"

#: module/plugins/hoster/MegaNz.py:118
msgid "Error code:"
msgstr "Code d'erreur :"

#: module/plugins/Container.py:68
msgid "File not exists."
msgstr "Le fichier n'existe pas."

#: module/plugins/hooks/UpdateManager.py:97
msgid "Not able to connect server to get updates"
msgstr "Impossible de se connecter au serveur pour obtenir les mises a jour"

#: module/plugins/hooks/UpdateManager.py:111
msgid "No pyLoad version available"
msgstr "Version de Pyload non disponible"

#: module/plugins/hooks/UpdateManager.py:118
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr "*** Nouvelle version %s disponible de pyLoad ***"

#: module/plugins/hooks/UpdateManager.py:119
msgid "***  Get it here: https://github.com/pyload/pyload/releases  ***"
msgstr "***  Obtenir ici : https://github.com/pyload/pyload/releases  ***"

#: module/plugins/hooks/UpdateManager.py:170
#, python-format
msgid "New version of [%(type)s] %(name)s (v%(oldver)s -> v%(newver)s)"
msgstr "Nouvelle version de [%(type)s] %(name)s (v%(oldver)s -> v%(newver)s)"

#: module/plugins/hooks/UpdateManager.py:180
#: module/plugins/hooks/UpdateManager.py:185
#, python-format
msgid "Error when updating plugin %s"
msgstr "Erreur au chargement du plugin %s"

#: module/plugins/hooks/UpdateManager.py:185
msgid "Version mismatch"
msgstr "Les versions discordent"

#: module/plugins/hooks/UpdateManager.py:196
#, python-format
msgid "Removed blacklisted plugin: [%(type)s] %(name)s"
msgstr "Supprimer les plugins indésirables : [%(type)s] %(name)s"

#: module/plugins/hooks/UpdateManager.py:204
msgid "Plugins updated and reloaded"
msgstr "Plugins mis à jour et rechargés"

#: module/plugins/hooks/UpdateManager.py:206
msgid "*** Plugins have been updated, pyLoad will be restarted now ***"
msgstr "*** les Plugin ont été mis à jour, pyLoad va redémarrer maintenant ***"

#: module/plugins/hooks/UpdateManager.py:211
msgid "No plugin updates available"
msgstr "Aucune mise à jour pour les plugins"

#: module/plugins/hooks/IRCInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr "Téléchargement terminé : %(name)s @ %(plugin)s "

#: module/plugins/hooks/IRCInterface.py:95
#, python-format
msgid "New Captcha Request: %s"
msgstr "Nouvelle demande de captcha : %s"

#: module/plugins/hooks/IRCInterface.py:96
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr "Répondre avec ' le texte c %s sur le captcha'"

#: module/plugins/hooks/Premium4Me.py:29
msgid "Please add your premium.to account first and restart pyLoad"
msgstr "Veuillez tout d'abord ajouter votre compte premium.to et redémarrez pyLoad"

#: module/plugins/hooks/HotFolder.py:81
#, python-format
msgid "Added %s from HotFolder"
msgstr "Ajout de %s à partir du HotFolder"

#: module/plugins/hooks/ExtractArchive.py:94
#, python-format
msgid "No %s installed"
msgstr "%s non installé"

#: module/plugins/hooks/ExtractArchive.py:96
#: module/plugins/hooks/ExtractArchive.py:101
#, python-format
msgid "Could not activate %s"
msgstr "Impossible d'activer %s"

#: module/plugins/hooks/ExtractArchive.py:106
msgid "Activated"
msgstr "Activé"

#: module/plugins/hooks/ExtractArchive.py:108
msgid "No Extract plugins activated"
msgstr "Pas de plugin d'extraction activé"

#: module/plugins/hooks/ExtractArchive.py:120
#, python-format
msgid "Package %s queued for later extracting"
msgstr "Le paquet %s est mis dans la file d'attente pour une extraction ultérieure"

#: module/plugins/hooks/ExtractArchive.py:143
#, python-format
msgid "Check package %s"
msgstr "Vérification du paquet %s"

#: module/plugins/hooks/ExtractArchive.py:184
#, python-format
msgid "Extract to %s"
msgstr "Extraction vers %s"

#: module/plugins/hooks/ExtractArchive.py:199
msgid "No files found to extract"
msgstr "Aucun fichier trouvé pour l'extraction"

#: module/plugins/hooks/ExtractArchive.py:206
msgid "extracting"
msgstr "extraction en cours"

#: module/plugins/hooks/ExtractArchive.py:217
msgid "Password protected"
msgstr "Mot de passe protégé"

#: module/plugins/hooks/ExtractArchive.py:238
msgid "Wrong password"
msgstr "Mot de passe incorrect"

#: module/plugins/hooks/ExtractArchive.py:246
#, python-format
msgid "Deleting %s files"
msgstr "Suppression de %s fichiers"

#: module/plugins/hooks/ExtractArchive.py:253
msgid "Extracting finished"
msgstr "Extraction terminée"

#: module/plugins/hooks/ExtractArchive.py:259
msgid "Archive Error"
msgstr "Erreur d'archive"

#: module/plugins/hooks/ExtractArchive.py:261
msgid "CRC Mismatch"
msgstr "CRC différents"

#: module/plugins/hooks/ExtractArchive.py:265
msgid "Unknown Error"
msgstr "Erreur inconnue"

#: module/plugins/hooks/ExtractArchive.py:317
msgid "Setting User and Group failed"
msgstr "La définition de l'utilisateur et du groupe a échoué"

#: module/plugins/hooks/ClickAndLoad.py:75
msgid "Click'N'Load: Port 9666 already in use"
msgstr "Click'N'Load : port 9666 déjà en cours d'utilisation"

#: module/plugins/hooks/CaptchaTrader.py:70
#: module/plugins/hooks/Captcha9kw.py:60
#: module/plugins/hooks/ExpertDecoders.py:51
#, python-format
msgid "%s credits left"
msgstr "%s crédits restants"

#: module/plugins/hooks/CaptchaTrader.py:118
msgid "Could not send response."
msgstr "Impossible d'envoyer une réponse."

#: module/plugins/hooks/CaptchaTrader.py:136
msgid "Your CaptchaTrader Account has not enough credits"
msgstr "Votre compte CaptchaTrader n'a pas assez de crédits"

#: module/plugins/hooks/LinkdecrypterCom.py:45
msgid "Crypter list not found"
msgstr "Liste des crypteurs non trouvée"

#: module/plugins/hooks/LinkdecrypterCom.py:59
msgid "Crypter list is empty"
msgstr "La liste des crypteurs est vide"

#: module/plugins/hooks/XMPPInterface.py:91
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr "Téléchargement fini : %(name)s @ %(plugin)s"

#: module/plugins/hooks/Captcha9kw.py:94
#, python-format
msgid "New CaptchaID from upload: %s : %s"
msgstr "Nouveau CaptchaID de l'upload: %s : %s"

#: module/plugins/hooks/Captcha9kw.py:130
msgid "Your Captcha 9kw.eu Account has not enough credits"
msgstr "Votre compte de captcha 9kw.eu n'a pas assez de crédits"

#: module/plugins/hooks/ExternalScripts.py:54
#, python-format
msgid "Installed scripts for %s: "
msgstr "Scripts installés pour %s : "

#: module/plugins/hooks/ExternalScripts.py:69
msgid "Script not executable:"
msgstr "Script non exécutable :"

#: module/plugins/hooks/ExternalScripts.py:80
#, python-format
msgid "Error in %(script)s: %(error)s"
msgstr "Erreur dans %(script)s : %(error)s"

#: module/plugins/hooks/ExpertDecoders.py:96
msgid "Your ExpertDecoders Account has not enough credits"
msgstr "Votre compte ExpertDecoders n'a pas assez de crédits"

#: module/plugins/hooks/RehostTo.py:32
msgid "Please add your rehost.to account first and restart pyLoad"
msgstr "Veuillez d'abord ajouter votre compte rehost.to et redémarrez pyLoad"

#: module/plugins/hooks/PremiumizeMe.py:50
msgid "Please add a valid premiumize.me account first and restart pyLoad."
msgstr "Veuillez d'abord ajouter un compte valide premiumize.me et redémarrez pyLoad."

#: module/plugins/hooks/CaptchaBrotherhood.py:70
#, python-format
msgid "%d credits left"
msgstr "%d crédits restants"

#: module/plugins/Plugin.py:389
msgid "Pil and tesseract not installed and no Client connected for captcha decrypting"
msgstr "Pil et tesseract ne sont pas installés et il n'y a pas de client connecté pour le déchiffrement des captcha"

#: module/plugins/Plugin.py:393
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr "Pas de résultats pour le captcha obtenu dans le temps impartis par aucun des plugins."

#: module/plugins/Plugin.py:498 module/plugins/Plugin.py:532
#, python-format
msgid "Setting User and Group failed: %s"
msgstr "La définition de l'utilisateur et du groupe a échoué :: %s"

#: module/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr "Pas de Client connecté pour le décryptage captcha"

#: module/Api.py:330
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr "Ajout package %(name)s contenant %(count)d liens"

#: module/Api.py:593
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr "Ajout de %(count)d liens au paquet #%(package)d "

#: module/common/JsEngine.py:156
msgid "No js engine detected, please install either Spidermonkey, ossp-js, pyv8 or rhino"
msgstr "Aucun moteur JS détecté, s'il vous plaît installez soit SpiderMonkey, ossp-js, pyv8 ou rhino"

